trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- script: |
    terraform init
    terraform validate
    terraform plan -out=tfplan
  displayName: 'Terraform Init and Plan'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)'
    artifactName: 'terraform-artifact'
    publishLocation: 'Pipeline'

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceName: 'AzureRM'
    commandOptions: '-auto-approve tfplan'
  displayName: 'Terraform Apply'
